apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager
  namespace: sample    # replace me
spec:
  resourceRequirementsEnabled: true
  monitoring:
    enabled: false
  system:
    redisPersistentVolumeClaim:
      storageClassName: ibmc-block-bronze
    database:
      mysql:
        persistentVolumeClaim:
          storageClassName: ibmc-block-bronze
    fileStorage:
      persistentVolumeClaim:
        storageClassName: ibmc-file-bronze-gid-custom
  backend:
    redisPersistentVolumeClaim:
      storageClassName: ibmc-block-bronze
  wildcardDomain: apps.mycluster.tckang.com   # replace me

  